### ISSUE TITLE
Discussion: Fairground organ cover.

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenMusic#16]
This page is the main discussion page for the merry-go-round style 

The following project is to replace the RCT2 fairground organ with both remastered as well as new songs to the merry-go-round.  
The songs need to fit the theme of the original.  

The plan is to collect all midi files of the songs, and then record this from an actual fairground organ.  
This of course all depends on the cost of hiring such equipment if we end up with recording this using midi or if we record an actual fairground organ. Research still has to be done.

**Comment by ccoors** [comment]
The organ in the original recordings is "The Bressingham Voigt", which is still [available for rent](https://www.draaivermaak.nl/Voigt_Herman) to this day. It is pretty likely that the original music books are still with this organ, so that might be the best chance to get a 'better' recording and/or even a 1:1-copy of the notes played. The fairground organ arrangements in this repo are not of very good quality so far, and probably never will be. I have given up on that project.

Chris Sawyer used the Copyright Tribunal Rules to legally take the music from a vinyl released in 1976, which was also called "The Bressingham Voigt", since he was unable to identify the performer ([link](https://www.thegazette.co.uk/notice/L-55338-301)). Under the same terms it might actually be possible to simply get one of those records and copy it again. People have even done it before, e.g. on [archive.org](https://archive.org/details/10TheBlondSailor).

Most fairground organs can not play MIDI files, but there are a few that were modified to do so. The [Museum Speelklok](https://www.museumspeelklok.nl/) has at least one. Keep in mind that making a good recording of a fairground organ is not an easy task, so getting one into a controlled environment or even recording studio would be best.

Making a fairground organ SoundFont would be an amazing thing, since to my knowledge there aren't any. There are companies specialized in making those too.

**Comment by IntelOrca** [comment]
Surely it is possible to replicate the sound of the organ with customisable vst synths?

**Comment by karst** [comment]
[Joris ten Have](https://draaiorgelarrangementen.nl/draaiorgelverhuur/) seems to have a few midi organs available too.

I personally think it would sound better to record a genuine organ rather than use a VST interpretation. If any VST has a decent one i imagine native instruments kontakt would have one

**Comment by karst** [comment]
I just found out that The Bressingham Voigt, the organ that was orginally recorded for RollerCoaster Tycoon, is currently owned and opperated by a fairground organ player a villager over from me. I am gonna see if I can use this to make new recordings with

**Comment by Derpercoaster** [comment]
There's loads of functional fairground organs (or at least similar ones) all over the world, and there's quite a few cases of people composing original music for them, so finding an organ with useable music will be really easy. Getting permission to record the audio might be hit-or-miss, though. The hard part will be finding thematically-appropriate music that is already composed (making new rolls is possible, but also expensive). Either way, I really hope this works out (and I also hope the original music stays in the game, please don't remove it).

**Comment by Mikroscopic** [comment]
I believe this person also has another organ of the same model. They've posted videos to their channel of it performing the same arrangements as the ones on the 1976 vinyl. Nearly identical look and sound as the Bressingham Voigt. No idea where they're located though.

https://www.youtube.com/@johankorten8106

**Comment by Derpercoaster** [comment]
> https://www.youtube.com/@johankorten8106

Gave some of these a listen. Perfection! These would fit so well in RCT! I guess I was wrong about good music being hard to find. Thanks for proving me wrong lol.

**Comment by karst** [comment]
Please check #26 for progress for the first addition. 
This also adds I believe two songs for the replacement.
